
github:
  prebuilds:
    master: true
    branches: true
    pullRequests: true
    pullRequestsFromForks: true
    addCheck: false
    addComment: false
    addBadge: true
tasks:
  - name: "build"
    init: yarn && yarn build
    command: yarn start
    env:
      SERVERLESS: false
      CLUSTER_ENABLED: false
      AUTH_ENABLED: false
      SSL_ENABLED: true
      SSL_PORT: 443
      PORT: 80
ports:
  - port: 8080
    onOpen: open-browser
  - port: 43300
    onOpen: open-browser
  - port: 5353 # for multicast DNS
    onOpen: notify 
