
github:
  prebuilds:
    master: true
    branches: true
    pullRequests: true
    pullRequestsFromForks: true
    addCheck: false
    addComment: false
    addBadge: true
tasks:
  - name: start
    init: yarn && yarn build
    command: yarn start
    env:
      SERVERLESS: false
      CLUSTER_ENABLED: false
      AUTH_ENABLED: false
      SSL_ENABLED: false
      SSL_PORT: 44300
      PORT: 8080
ports:
  - port: 8080
    onOpen: open-preview
  - port: 44300
    onOpen: open-preview
  - port: 5353 # for multicast DNS
    onOpen: ignore 
