
github:
  prebuilds:
    master: true
    branches: true
    pullRequests: true
    pullRequestsFromForks: true
    addCheck: false
    addComment: false
    addBadge: true
tasks:
  - name: "build order"
    init: yarn && yarn build-order
    command: yarn start
    env:
      IS_SWITCH: true # designate as primary mesh server
      SERVERLESS: false
      CLUSTER_ENABLED: false
      AUTH_ENABLED: false
      SSL_ENABLED: false
      PORT: 8080
      GITHUB_TOKEN: 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
ports:
  - port: 8080
    onOpen: open-browser
  - port: 5353 # for multicast DNS
    onOpen: notify 